### ISSUE TITLE
Combined AEAD ChaCha/Poly

### ISSUE THREAD

**Issue by wintersteiger** [tfaoliveira/libjc#2]
Is there a complete and verified AEAD ChaCha+Poly implementation in Jasmin or are only the primitives available for now?

**Comment by bgregoir** [comment]
Hi, 
  As far as I known, only the primitives are available for now.
  But this is something that we plan to do, in particular we plan to do also the formal security proof (i.e exact security).
Best,
   Benjamin

**Comment by wintersteiger** [comment]
Great, that's good to know, thanks!
